[package]
name = "blacksholes_rust"
version = "0.1.0"
edition = "2024"


# This creates both a library and a binary
[lib]
path = "src/lib.rs"

[[bin]]
name = "blacksholes_rust"  # Optional if same as package name
path = "src/main.rs"


[[bench]]
name = "criterion_benchmark"
harness = false  # Disables default libtest harness for Criterion.rs

[profile.release]
debug = true               # Maximum debug info
opt-level = 3           # Keep optimizations
strip = false

[profile.bench]
debug = true              # Maximum debug info
opt-level = 3           # Keep optimizations
strip = false

[dev-dependencies]
pprof = { version = "0.14.0", features = ["flamegraph", "criterion"] }
criterion = { version= "0.5.1", features = ["html_reports"] }


[dependencies]
approx = "0.5.1"
libm = "0.2.11"
async-stream = "0.3.6"
futures = "0.3.31"
futures-signals = "0.3.34"
rand = "0.9.0"
tokio = {  version = "1.44.1", features = ["time", "rt", "macros", "rt-multi-thread", "signal"] }
time = "0.3.41"
libc = "0.2.171"
rand_distr = "0.5.1"
rayon = "1.10.0"
dhat = "0.3.3"
